version: '3'
services:
  stash1:
    image: stashapp/stash:latest
    container_name: stash1
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./media:/media
      - ./config/stash1:/root/.stash
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
  stash2:
    image: stashapp/stash:latest
    container_name: stash2
    restart: unless-stopped
    ports:
      - 9998:9999
    volumes:
      - ./media:/media
      - ./config/stash2:/root/.stash
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
  downloader:
    #image: shogun1903/stash-downloader:latest
    build: .
    container_name: stash-downloader
    restart: "no"
    ports:
      - 5000:5000
    volumes:
      - ./media:/media
    environment:
      - STASH_MEDIA_PATH=/media/
      - DEBUG=false
      - STASH_SCAN_TIMEOUT=5
