version: '3'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./media:/media
      - ./config:/root/.stash
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
  downloader:
    image: shogun1903/stash-downloader:latest
    build: .
    container_name: stash-downloader
    restart: "no"
    ports:
      - 5000:5000
    volumes:
      - ./media:/media
    environment:
      - STASH_DOMAIN=stash
      - STASH_PORT=9999
      - STASH_MEDIA_PATH=/media/
      - DEBUG=false
      - STASH_STAR_DOMAIN=stash
      - STASH_STAR_PORT=9999
      - STASH_STAR_LIB=stars
      - STASH_SCAN_TIMEOUT=5
